name: Docker Image for Front (Buzgibi)

on: 
  push:
    branches: 
      - master
        # Pattern matched against refs/tags
    tags:        
      - '*' # Push events to every tag not containing /

jobs:

  push_to_google_registry:
    name: Push Docker image to Google
    environment: google
    runs-on: ubuntu-latest
    steps:    
      - name: Check out the repo
        uses: actions/checkout@v3.5.2

      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: europe-west3-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Docker meta tag
        id: meta_tag_1
        uses: docker/metadata-action@v4
        if: ${{ contains(github.ref_type, 'tag') }}
        with:
          images: |
            ${{ vars.DOCKER_IMAGE }}   
          tags: |
            type=raw,value=${{ github.ref_name }}
            
      - name: Docker meta branch
        id: meta_branch_1
        uses: docker/metadata-action@v4 
        if: ${{ contains(github.ref_type, 'branch') }}
        with:
          images: |
            ${{ vars.DOCKER_IMAGE }}
          tags: |       
            type=raw,value=${{ github.ref_name }}_${{ github.sha }},enable=${{ github.ref == format('refs/heads/{0}', github.ref_name) }}
            type=raw,value=latest
                
      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta_tag_1.outputs.tags }}
            ${{ steps.meta_branch_1.outputs.tags }}

  deploy:
    name: Deploy the server
    runs-on: ubuntu-latest
    environment: google
    needs: push_to_google_registry
    steps:
      - uses: actions/checkout@v2
      - uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
              cd back
              docker-compose down front
              docker-compose up front -d    